vcptuWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vcptu_home.urls', namespace='vcptu_home')),
    path('about-us', include('vcptu_about.urls', namespace='vcptu_about')),
    path('facility', include('vcptu_facility.urls', namespace='vcptu_facility')),
    path('team', include('vcptu_team.urls', namespace='vcptu_team')),
    path('publications', include('vcptu_publication.urls', namespace='vcptu_publication')),
    path('projects', include('vcptu_project.urls', namespace='vcptu_project')),
    path('acreditation', include('vcptu_accreditation.urls', namespace='vcptu_accreditation')),
    path('our-contacts', include('vcptu_contact.urls', namespace='vcptu_contact')),
    path('latest-news', include('vcptu_news.urls', namespace='vcptu_news')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

vcptu_home/urls.py
from django.urls import path

from . import views

app_name = 'vcptu_home'

urlpatterns = [
    path('', views.homePage, name="homePage")
]

vcptu_news/urls.py
from django.urls import path

from . import views

app_name = 'vcptu_news'

urlpatterns = [
    path('', views.newsPage, name="newsPage"),
    path('news-details/<str:id>/', views.newsDetailPage, name="newsDetailPage")
]

templates/newsPage/newsDetailPage.html
{% extends '../baseTemplates/base.html' %}
{% load static %}
{% block title %} news-Detail {% endblock %}
{% block content %}

<div class="section_for_news">
    <div class="container-fluid">
        {% if get_news_detail %}
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <!-- <h2>Latest news</h2> -->
                <div class="inner_section" data-aos='zoom-out-up'>
                    <div class="image_section">
                        <img src="{{ get_news_detail.upload_image.url }}" alt="" class="img-fluid">
                    </div>
                    <div class="news_description">
                        <h3>{{get_news_detail.news_main_title }}</h3>

                        <p> {{get_news_detail.descriptions|safe }}
                        </p>

                    </div>
                   
                </div>
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% include '../components/footer.html' %}


{% endblock %}

templates/newsPage/newsPage.html
{% extends '../baseTemplates/base.html' %}
{% load static %}
{% block title %} Latest-news {% endblock %}
{% block content %}
<div class="section_for_news">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8 offset-md-2">
                <div class="inner_section" data-aos='zoom-out-up'>
                    <div class="other_news">
                        {% if get_all_news %}
                        {% for news in get_all_news %}
                        <div class="container" data-aos='zoom-out-up' style="border-bottom: 0.1px solid #eee;">
                            <a href="{% url 'vcptu_news:newsDetailPage' news.id  %}" class="link" style="text-decoration:none;color:#000;">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="image_section">
                                            <img src="{{ news.upload_image.url }}" alt="" class="img-fluid" style="width:100%;height:90%;padding: 5px;">
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <h3>{{ news.news_main_title }}</h3>

                                        <p>{{ news.descriptions|safe  }}</p>

                                        <p class="read_more" style="border: 1px solid green ;border-radius:15px;padding:10px 10px;display:inline-block">Read more</p>
                                    </div>
                                </div>
                            </a>

                        </div>
                        {% endfor %}
                        {% else %}
                        <div class="empty-section">
                            <p>No Content</p>
                        </div>
                        {% endif %}



                    </div>
                </div>
            </div>
        </div>
    </div>
    {% include '../components/footer.html' %}

    {% endblock %}
 