vcptuWebsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('vcptu_home.urls', namespace='vcptu_home')),
    path('about-us', include('vcptu_about.urls', namespace='vcptu_about')),
    path('facility', include('vcptu_facility.urls', namespace='vcptu_facility')),
    path('team', include('vcptu_team.urls', namespace='vcptu_team')),
    path('publications', include('vcptu_publication.urls', namespace='vcptu_publication')),
    path('projects', include('vcptu_project.urls', namespace='vcptu_project')),
    path('acreditation', include('vcptu_accreditation.urls', namespace='vcptu_accreditation')),
    path('our-contacts', include('vcptu_contact.urls', namespace='vcptu_contact')),
    path('latest-news', include('vcptu_news.urls', namespace='vcptu_news')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

vcptu_about/urls.py
from django.urls import path

from . import views

app_name = 'vcptu_about'

urlpatterns = [
    path('', views.aboutPage, name="aboutPage")
]

vcptu_contact/urls.py
from django.urls import path

from . import views

app_name = 'vcptu_contact'

urlpatterns = [
    path('', views.contactPage, name="contactPage")
]

vcptu_home/urls.py
from django.urls import path

from . import views

app_name = 'vcptu_home'

urlpatterns = [
    path('', views.homePage, name="homePage")
]

vcptu_news/urls.py
from django.urls import path

from . import views

app_name = 'vcptu_news'

urlpatterns = [
    path('', views.newsPage, name="newsPage"),
    path('news-details/<str:id>/', views.newsDetailPage, name="newsDetailPage")
]

vcptu_team/urls.py
from django.urls import path

from . import views

app_name = 'vcptu_team'

urlpatterns = [
    path('', views.teamPage, name="teamPage"),
    path('team-Detail/<str:id>/', views.teamDetailPage, name="teamDetailPage")
]

templates/components/contributors.html
{% load static %}
<div class="contributors_list">
  {% for contributor in get_all_user_or_cotributors %}
    {% if contributor.member_photo %}
      <img src="{{ contributor.member_photo.url }}" alt="">
    {% else %}
      <img src="{% static 'images/avatar.png' %}" alt="">
    {% endif %}
  {% endfor %}
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
  <img src="{% static 'images/avatar.png' %}" alt="">
</div>

templates/components/footer.html
{% load static %}
<div class="footer_section" style="padding: 40px 70px;">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-4">
        <div class="item">
          <!-- <img src="{% static './images/logo.png' %}" alt="" class="img-fluid" style="width: 300px;"> -->
          <div class="address">
            <p><a href="">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-geo-alt-fill" viewBox="0 0 16 16">
                  <path d="M8 16s6-5.686 6-10A6 6 0 0 0 2 6c0 4.314 6 10 6 10zm0-7a3 3 0 1 1 0-6 3 3 0 0 1 0 6z" />
                </svg> P.O. Box 74, Bagamoyo</a></p>
            <p class="text-white"><a href="">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone-inbound" viewBox="0 0 16 16">
                  <path d="M15.854.146a.5.5 0 0 1 0 .708L11.707 5H14.5a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5v-4a.5.5 0 0 1 1 0v2.793L15.146.146a.5.5 0 0 1 .708 0zm-12.2 1.182a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                </svg> +255 232 440065</a></p>
            <p><a href="mailto:VCPTUmgt@ihi.or.tz" target="_self" title="VCPTUmgt@ihi.or.tz">

                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                  <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
                </svg> VCPTUmgt@ihi.or.tz</a></p>
            <p><a href="">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-globe" viewBox="0 0 16 16">
                  <path
                   d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm7.5-6.923c-.67.204-1.335.82-1.887 1.855A7.97 7.97 0 0 0 5.145 4H7.5V1.077zM4.09 4a9.267 9.267 0 0 1 .64-1.539 6.7 6.7 0 0 1 .597-.933A7.025 7.025 0 0 0 2.255 4H4.09zm-.582 3.5c.03-.877.138-1.718.312-2.5H1.674a6.958 6.958 0 0 0-.656 2.5h2.49zM4.847 5a12.5 12.5 0 0 0-.338 2.5H7.5V5H4.847zM8.5 5v2.5h2.99a12.495 12.495 0 0 0-.337-2.5H8.5zM4.51 8.5a12.5 12.5 0 0 0 .337 2.5H7.5V8.5H4.51zm3.99 0V11h2.653c.187-.765.306-1.608.338-2.5H8.5zM5.145 12c.138.386.295.744.468 1.068.552 1.035 1.218 1.65 1.887 1.855V12H5.145zm.182 2.472a6.696 6.696 0 0 1-.597-.933A9.268 9.268 0 0 1 4.09 12H2.255a7.024 7.024 0 0 0 3.072 2.472zM3.82 11a13.652 13.652 0 0 1-.312-2.5h-2.49c.062.89.291 1.733.656 2.5H3.82zm6.853 3.472A7.024 7.024 0 0 0 13.745 12H11.91a9.27 9.27 0 0 1-.64 1.539 6.688 6.688 0 0 1-.597.933zM8.5 12v2.923c.67-.204 1.335-.82 1.887-1.855.173-.324.33-.682.468-1.068H8.5zm3.68-1h2.146c.365-.767.594-1.61.656-2.5h-2.49a13.65 13.65 0 0 1-.312 2.5zm2.802-3.5a6.959 6.959 0 0 0-.656-2.5H12.18c.174.782.282 1.623.312 2.5h2.49zM11.27 2.461c.247.464.462.98.64 1.539h1.835a7.024 7.024 0 0 0-3.072-2.472c.218.284.418.598.597.933zM10.855 4a7.966 7.966 0 0 0-.468-1.068C9.835 1.897 9.17 1.282 8.5 1.077V4h2.355z" />
                </svg> www.vcptu.or.tz</a></p>
          </div>
        </div>
      </div>

      <div class="col-md-2">
        <div class="item">
          <h5>Quick links</h5>
          {% include '../components/whiteLine.html' %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'vcptu_home:homePage' %}">
                Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_about:aboutPage' %}"> About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_facility:facilityPage' %}">
                Facility</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_team:teamPage' %}">
                Team</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_contact:contactPage' %}">
                Contact</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2">
        <div class="item">
          <h5>Research</h5>
          {% include '../components/whiteLine.html' %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_publication:publicationPage' %}">Publication</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_project:projectPage' %}">Project</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_accreditation:accreditationPage' %}">Accreditations</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="col-md-2">
        <div class="item">
          <h5>Accreditations</h5>
          {% include '../components/whiteLine.html' %}
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_publication:publicationPage' %}">Publication</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_project:projectPage' %}">Project</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'vcptu_accreditation:accreditationPage' %}">Accreditations</a>
            </li>
          </ul>
        </div>
      </div>

      {% include '../components/whiteLine.html' %}
      <p class="text-center p-4">{{CURRENT_YEAR}} @ Ifakara Health Institute. All right reserved.</p>
    </div>

  </div>

</div>

templates/components/heroSectionWithVideo.html
{% load static %}
<!-- <div id="hero">
  <video playsinline autoplay muted loop poster="placeholder.jpg" id="bgvideo" width="100%" height="100vh">
  <source src="{% static './videos/test.mp4' %}" type="video/mp4">
  </video>
  <div class="front_text">
    <div class="container">
      <div class="row">
        <div class="col-md-8 offset-md-2">
          <div class="item" data-aos="zoom-in-up">
            <h1>VECTOR PROJECT TESTING UNIT</h1>
            <h5><strong>We check  & Recheack our result</strong></h5>
            <div class="button_section">
              <a href="" class="our_service_link" >view our services</a>
            </div> 
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div> -->
<!-- 
<header>
  <div class="overlay"></div>
  <video playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop" data-video="0">
    
      <source src="{% static './videos/test.mp4' %}" type="video/mp4">
    
  </video>
  <div class="container h-100">
    <div class="d-flex h-100 text-center align-items-center">
      <div class="w-100 text-white">
        <h1 class="wow zoomIn" data-wow-delay="1s">We're a world class research Institute</h1>
        <h2 class="lead mb-0 wow fadeIn" data-wow-delay="2s"> We exist to improve health and wellbeing of people</h2>
      </div>
    </div>
  </div>
</header> -->


<!-- <video loop muted autoplay playsinline poster="URL/TO/poster.jpg" class="background-video">
  <source src="{% static './videos/test.mp4' %}" type="video/mp4">
  <source src="URL/TO/video.webm" type="video/webm">
  <source src="URL/TO/video.ogv" type="video/ogv">
</video>

<div class="background-video-content">
  Your Element content in here.
</div> -->


<header>
  <!--- header --->
</header>

<main>
  <section id="hero-video">
    <div id="hero">
  <video playsinline autoplay muted loop poster="placeholder.jpg" id="bgvideo" width="100%" height="100vh">
  <source src="{% static './videos/Ifakara Health Institute.mp4' %}" type="video/mp4">
  </video>
  <div class="front_text">
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <div class="item" data-aos="zoom-in-up">
            <h1>VECTOR CONTROL PRODUCT</h1>
            <h1>TESTING UNIT</h1>
            <h5><strong>We check  & Recheack our result</strong></h5>
            <div class="button_section">
              <a href="{% url  'vcptUnit_service:servicesPage' %}" class="our_service_link" >view our services</a>
            </div> 
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>
  </section>
</main>

templates/components/horizontalLine.html
<div class="green_horizontal_line_section">
</div>

templates/components/map.html
<div class="map_section">
  <div class="container-fluid" style="padding: 0px">
    <div class="row">
      <div class="col-md-12">
        <div class="map">
          <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3962.0296318445317!2d39.2519769143459!3d-6.7662413680460975!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x185c4c36c47c32eb%3A0x8cc0e4ec01f66ed5!2sIfakara%20Health%20Institute%20(IHI)!5e0!3m2!1sen!2stz!4v1671778003634!5m2!1sen!2stz"
            width="100%"
            height="450"
            style="border: 0; margin: 0px; padding: 0px; background-color: #fff"
            allowfullscreen=""
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade"
          ></iframe>
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/messageFromDirector.html
{% load static %}
<div class="messages_section">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="inner">
          <div class="message">
            <h4>Message from Head of Unit</h4>
            {% include 'components/topHorizontalLIne.html' %}
            <div style="width: 270px;">
            
            </div>
           
              <p><q>
                We serve the community through excellence in service delivery, research into new methods of product testing and training of MSc and PhD students.

                Having a diverse range of vector control tools in the malaria control toolbox has two advantages: 1) malaria control programs can select tools most suitable for their setting and 2) increasing market diversity creates competition that drives down unit costs of products.
              </q></p>
          
          </div>
          <div class="image_section" data-aos="slide-left">
            <a href="{% url 'vcptUnit_team:SaraahMooredetailView' %}" class="link" style="text-decoration: none;color: black;">

            <img src="{% static './images//Dr -saraah.JPG' %}" alt="" class="img-fluid">
            <div class="title">
              <h5>Dr Sarah Moore</h5>
              <h6> Head of unit</h6>
            </div>
          </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/mission.html
<div class="vcptu_history_section">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div class="inner_section">
					<div class="header" style="height:220px">
						<h4 data-aos="slide-up"><strong>Mission</strong></h4>
						<p data-aos="slide-up">Our mission is to bring new vector control products to market more rapidly and cost-efficiently through the conduct of rigorous evaluations using well powered studies, enhanced research standards, and careful data analysis. At the same time, we are dedicated to building capacity in entomology for the future of vector control.</p>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

templates/components/navigation.html
{% load static %}
<div class="navigation_section_one">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="inner_section">
          <div class="logo_section" style="display: flex;">
          
              <img src="{% static './images/ihi.jpeg' %}" alt="" class="img-fluid " style="width:120px;padding: 10px 10px;">
              <div class="vertical_green_line" style="width:2px;height: 50px;background-color: green;margin-top:20px ;"></div>
            <img src="{% static './images/vcptuLogo.jpg' %}" alt="" class="img-fluid " style="width:120px;padding: 10px 10px;">
          </div>
          <div class="address_section ">
            <div class="item1" style="display: flex;">
              <div class="image_section">
                <img src="{% static './images/SANAS-Logo.png' %}" alt="" class="img-fluid" style="width: 150px;padding: 10px 10px;">
              </div>
              <!-- <div class="description" style="padding-top: 15px;color: black;">
                <h6>
                  Bagamoyo Branch</h6>
                <span>Off Chuguni Road - Bagamoyo</span>
              </div> -->
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="navigation_section_two" style="box-shadow: rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <hr style="padding: 1px;margin: 1px;">
        <div class="item">

          <nav class="navbar navbar-expand-lg">
            <div class="button_section">
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
            <div class="collapse navbar-collapse  " id="navbarSupportedContent">
              <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                  <a class="nav-link active" aria-current="page" href="{% url 'vcptu_home:homePage' %}">Home</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptu_about:aboutPage' %}">About</a>
                </li>
              
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptu_facility:facilityPage' %}">Facility</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptu_team:teamPage' %}">Team</a>
                </li>

                <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Research
                  </a>
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'vcptu_publication:publicationPage' %}">Publication</a></li>
                    <li><a class="dropdown-item" href="{% url 'vcptu_project:projectPage' %}">Project</a></li>
                  </ul>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptu_accreditation:accreditationPage' %}">Accreditations</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptu_news:newsPage' %}">News</a>
                </li>

                <li class="nav-item">
                  <a class="nav-link" href="{% url 'vcptu_contact:contactPage' %}">Contact</a>
                </li>
              
                  <li class="nav-item">
                    <button type="button" class="btn btn-outline-white p-0" data-bs-toggle="modal" >
                      <span class="nav-link"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                          <path d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                        </svg>
                    </button>
                  </li>
              </ul>
            </div>

          </nav>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" tabindex="0" >
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h1 class="modal-title fs-5" id="staticBackdropLabel">Serch content</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
              <div class="modal-body">
                <form action="">
                  <input type="text" class="form-control">
                </form>
              </div>
              <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/publication.html
{% load static %}
<div class="publication_section_at_home_page">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="title text-center">
          <h3>Latest Publications</h3>
        </div>
        <div class="inner_section">
          <div class="publication"  data-aos="zoom-in-up">
            <div class="icon" style="width: 100px;">
              <img src="{% static './images/publication.png' %}" alt="" class="img-fluid" width="100%">
            </div>
            <div class="desciption">
              
              <p>1. Edith P. Madumla, Olukayode G. Odufuwa, Edgar M. Mbeyela, Godfrey Ligema and Sarah J. Moore. <i>Large-scale (Phase III) evaluation of survivorship, biological efficacy, fabric integrity and community acceptability of DawaPlus®2.0 long-lasting insecticidal nets compared with PermaNet®2.0 in Kilombero, Tanzania. Mal J.</i></p>
            </div>
          </div>
          <div class="publication"  data-aos="zoom-in-up">
            <div class="icon" style="width: 100px;">
              <img src="{% static './images/publication.png' %}" alt="" class="img-fluid" width="100%">
            </div>
            <div class="desciption">
              
              <p>2. Olukayode G. Odufuwa, John Bradley, Zawadi Mageni Mboma, Emmanuel Mbuba, Joseph B. Muganga, Rose Philipo, Jason Moore, Ole Skovmand, Sarah Jane Moore. <i>The influence of time of experiment, insecticide resistance levels and post exposure holding time on the bioefficacy of insecticides against metabolic resistant mosquitoes.  Parasites and Vectors</i>.</p>
            </div>
          </div>
          
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/topHorizontalLIne.html
<div class="top_horizontal_line">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-12">
        <div class="line">
        </div>
      </div>
    </div>
  </div>
</div>

templates/components/vcptuStaff.html
{% load static %}
<div class="staff_section">
  <div class="container-fluid">
    <div class="row">
      <div class="col-md-6 offset-md-3">
        <div class="staff">
          <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-indicators">
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
              <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <div class="inner_item" style="background-color: aliceblue;">
                  <img src="{% static './images/Dr-Sarah-Moore-VCPTU-335x335-1.jpg' %}" class="d-block w-100 img-fluid img-circle" alt="..." style="width: 100px;height: 410px;border-radius: 100%;">
                  <div class="carousel-caption d-none d-md-block">
                  <h5>Dr Sarah Moore</h5>
                  <p>Head of Unit.</p>
                </div>
                </div>
              </div>
              <div class="carousel-item">
                <img src="{% static './images/Dr-Sarah-Moore-VCPTU-335x335-1.jpg' %}" class="d-block w-100 img-fluid" alt="..." style="width: 100px;height: 410px;border-radius: 100%;">
                <div class="carousel-caption d-none d-md-block">
                  <h5>Second slide label</h5>
                  <p>Some representative placeholder content for the second slide.</p>
                </div>
              </div>
              <div class="carousel-item">
                <img src="{% static './images/Dr-Sarah-Moore-VCPTU-335x335-1.jpg' %}" class="d-block w-100" alt="..." style="width: 100px;height: 410px;border-radius: 100%;">
                <div class="carousel-caption d-none d-md-block">
                  <h5>Third slide label</h5>
                  <p>Some representative placeholder content for the third slide.</p>
                </div>
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>